# Generated by Django 6.0.3 on 2026-03-23 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.URLField()),
                ('category', models.CharField(choices=[('modern', 'Modern'), ('professional', 'Professional'), ('minimal', 'Minimal'), ('creative', 'Creative')], max_length=20)),
                ('is_pro', models.BooleanField(default=False)),
            ],
        ),
    ]
