# Generated by Django 6.0.3 on 2026-03-23 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='image',
            field=models.ImageField(upload_to='templates/'),
        ),
    ]
