# Generated by Django 5.0 on 2026-03-24 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0002_alter_template_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
