# Generated by Django 5.0 on 2026-03-24 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0003_alter_template_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='templates/'),
        ),
    ]
